@startuml diagram

class Point{
   + x
   + y
}

class Feature{
   - name: String
   - p : Point[]
   - type : Types
   - cat : Category
}

class Loader{
   + updateChunk(p1:Point, p2:Point) : Chunk[]
}

class Chunk{

}

class Category{
   - name : String
   - fillColor : String
   - strokeColor : String
   - textColor : String
   - police : String
   - level : int
   - icon : Image
   - zoomable: bool
   - displayName: bool
   - extendsFrom : String[]
   'pour le pathfinding
   - attribut: String[] 
}
class Image{
   - path : String
}

Feature --o Point
Feature -- Types
Category -- Image
Category --o Feature

@enduml