@startuml dataBuildSequenceOSM

Map -> OSMParser : parse(props)
OSMParser <-> OSMParser --++ : XML -> OSM

OSMParser -> PortalParser ++ : parse(Coords, Style)
OSMParser <- PortalParser -- : Items (spinel)

activate OSMParser
deactivate OSMParser
Map <- OSMParser -- : PlainMap

@enduml