@startuml spinel
package spinel{
    package utils {}
    package scheduling {}
    package math {}
    package gfx {}
    package elements {
    }
    class Window
    class Input
    class Engine implements java.lang.Runnable

    utils <-[hidden]- Window
    math <-[hidden]- Engine
    elements <-[hidden]- Input
}



@enduml